### ISSUE TITLE
Error Code :2011-0301 (0x25a0b)

### ISSUE THREAD

**Issue by psychovsky** [mklan/NX-Rom-Market#1]
I have these errors.

erista, retroreloaded pro, atmosphere 17, fw 11.0.1
![313490AF-4068-4B43-BCD0-6069150AE207](https://user-images.githubusercontent.com/77238798/104127413-02e77600-5373-11eb-9e94-a1bdcc08a535.jpeg)
![F06F81CC-A281-452B-AFBC-ECAF739CE1D9](https://user-images.githubusercontent.com/77238798/104127420-0975ed80-5373-11eb-89a5-bb664ed15594.jpeg)

**Comment by mklan** [comment]
Hey I updated main.py to remove a duplicate json package import. Could you try to update main.py with the new content? Also how does your collections.json file look like?

**Comment by psychovsky** [comment]
> Hey I updated main.py to remove a duplicate json package import. Could you try to update main.py with the new content? Also how does your collections.json file look like?

{
  "N64": "SomeRomCollectionByGhostw***",
  "SNES": "SomeOtherCollectionByGhostw***"
}

same result same errors

**Comment by mklan** [comment]
Can you try to add this homebrew and run it?

https://github.com/nx-python/PyNX/releases/tag/v0.6.0-alpha

maybe it could be fw 11.0.1. I am still on 10

**Comment by psychovsky** [comment]
> Can you try to add this homebrew and run it?
> 
> https://github.com/nx-python/PyNX/releases/tag/v0.6.0-alpha
> 
> maybe it could be fw 11.0.1. I am still on 10


yes i tried it's the same situation

**Comment by mklan** [comment]
OK are you using Fusee-Primary as your bootloader? I will try to update to 11.0.1 and test it

**Comment by psychovsky** [comment]
> OK are you using Fusee-Primary as your bootloader? I will try to update to 11.0.1 and test it


I am not familiar with other cfws because I used sx before. i have dual booter app named retroreloaded.

Probably fusee if I use atmospehere.
