### ISSUE TITLE
Wrong JSON Format!

### ISSUE THREAD

**Issue by dachimiriani** [mklan/NX-Rom-Market#2]
Hello,
When I downloaded this app, I wanted to add every collection/set I could find from the *person* on archive.org. I took some time and added them altogether. When I launched the app, it displayed a message, saying: "Wrong JSON Format! Check collections.json". Is it because of the special characters, or what?
Any help would be appreciated.
Thanks.

**Comment by mklan** [comment]
Hey, it could be that you have a trailing comma in the last entry? JSON is very strict about this. you can use https://jsonlint.com/ to see what exactly is wrong

**Comment by mklan** [comment]
you can also email me your json matthias.klan@gmail.com and I can have a look at it

**Comment by dachimiriani** [comment]
Oh, nevermind, I just noticed a period, instead of a comma. I changed it and it worked.
Thank you for taking your time.
