### ISSUE TITLE
Collections Questions

### ISSUE THREAD

**Issue by sskyNS** [mklan/NX-Rom-Market#6]
Please tell me how can I get these identifiers from this website, I can't find it, is there any detailed example I can refer to

**Comment by 16BitWonder** [comment]
Identifiers are part of a collection's URL, and listed in the description.
Ex: https://archive.org/details/boss_dd2-sm
Its identifier is "boss_dd2-sm" after "details/"

Alternatively you can scroll down on the collection page and find the listed identifier in the details.
![image](https://github.com/mklan/nx-archive-browser/assets/25729145/3489ed99-449c-4bd9-82c7-367fcfca682a)

**Comment by sskyNS** [comment]
thanks very much~
